version: '3.8'
services:
  statistic:
    build: ./statistic
    container_name: statistic
    ports:
      - "9090:9090"
    depends_on:
      - statistic-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/statistic-db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
    restart: always

  statistic-db:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=statistic-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=iamroot
    restart: always

  service:
    build: ./service
    container_name: service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - STATS_SERVER_URL=http://localhost:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/expl-db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=iamroot
    restart: always

  ewm-db:
    image: postgres:14-alpine
    ports:
      - "6541:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=expl-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=iamroot
    restart: always

